### ISSUE TITLE
Modify coverages file

### ISSUE THREAD

**Issue by emunte** [bihealth/clear-cnv#6]
Dear developers,

I am starting to work with clear-cnv and I have one comment. 
When I apply the matschores function using the coverages file obtained by workflow_reassignment I obtain the following error: 

`Exception: File needs to be formatted like: chr	start	end	gene	sample_0	sample_1	sample_n`

I have realized that it is due to a missing column in the coverages file (the gene column). 
So this error can be solved if the gene column is added, however, in my opinion manipulating files  can be error-prone. I suggest it would be very nice if the coverages file could incorporate the gene column.

Thanks for your work,

Eli

**Comment by vinzenzmay** [comment]
Hi Eli,
thank you very much for your advice. Beware that this "hack" only works if your data was generated on only one gene panel. If you have two or more bed files, then they get merged and the coverages are computed on this new big bed file, thereby they become unusable for CNV calling.

Please be aware that a panel re-assignment is usually not necessary if you have only one gene panel. Just start with the `workflow_cnv_calling` step and take a look at the QC files to see if your data is somewhat evenly distributed. ClearCNV's CNV calling is able to handle batch effects to a certain degree.

If you are certain that you need to separate batches even before you have seen the QC files, then you can indeed apply this little hack of re-using the coverages.

In any case, I really recommend to use `workflow_cnv_calling` instead of the single steps involved there. This also protects you from using data in the wrong spot.

I hope I understand correctly that you have only one bed file in your analysis but several batches. Otherwise I'd need some more feedback to find out what just happened there.

Cheers!
Vinzenz

**Comment by emunte** [comment]
Thank you Vinzenz!
